version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
  php:
    build: docker/php7-fpm
    env_file: ./.env
    volumes:
      - ./logs/symfony:/var/www/symfony/app/logs
    links:
      - db
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
  node:
    build: docker/node
    expose:
      - 8080
    volumes:
      - ./logs/node:/var/log/node
      - /app/node_modules
    command: npm start